name: Run Tests
on: push

jobs:
  run_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Format and lint
        run: |
          black . --check
          flake8 .

      - name: Run tests suite
        run: |
          pytest .
